name: fashion_lens
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.6
  image_picker: ^1.1.2
  animated_bottom_navigation_bar: ^1.3.3
  camera: ^0.11.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/man.png
    - assets/woman.png
    - assets/man/
    - assets/woman/
    - assets/man/jacket.png
    - assets/man/shortpants.png
    - assets/man/longpants.png
    - assets/man/sweater.png
    - assets/man/shirt.png
    # - assets/man/man_jacket/1.png
    # - assets/man/man_jacket/2.png
    # - assets/man/man_jacket/3.png
    # - assets/man/man_jacket/4.png
    # - assets/man/man_jacket/5.png
    # - assets/man/man_jacket/6.png
    - assets/man/man_jackets/male_jacket_1.png
    - assets/man/man_jackets/male_jacket_2.png
    - assets/man/man_jackets/male_jacket_3.png
    - assets/man/man_jackets/male_jacket_4.png
    - assets/man/man_jackets/male_jacket_5.png
    - assets/man/man_jackets/male_jacket_6.png
    - assets/man/man_shortpants/male_short_1.png
    - assets/man/man_shortpants/male_short_2.png
    - assets/man/man_shortpants/male_short_3.png
    - assets/man/man_shortpants/male_short_4.png
    - assets/man/man_shortpants/male_short_5.png
    - assets/man/man_shortpants/male_short_6.png
    - assets/man/man_longpants/male_pants_1.png
    - assets/man/man_longpants/male_pants_2.png
    - assets/man/man_longpants/male_pants_3.png
    - assets/man/man_longpants/male_pants_4.png
    - assets/man/man_longpants/male_pants_5.png
    - assets/man/man_longpants/male_pants_6.png
    - assets/man/man_sweater/male_sweatshirt_1.png
    - assets/man/man_sweater/male_sweatshirt_2.png
    - assets/man/man_sweater/male_sweatshirt_3.png
    - assets/man/man_sweater/male_sweatshirt_4.png
    - assets/man/man_sweater/male_sweatshirt_5.png
    - assets/man/man_sweater/male_sweatshirt_6.png
    - assets/man/man_shirt/male_tshirt_1.png
    - assets/man/man_shirt/male_tshirt_2.png
    - assets/man/man_shirt/male_tshirt_3.png
    - assets/man/man_shirt/male_tshirt_4.png
    - assets/man/man_shirt/male_tshirt_5.png
    - assets/man/man_shirt/male_tshirt_6.png
    